base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'l_wheel_joint'
  right_wheel: 'r_wheel_joint'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  publish_rate: 50

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.374
  wheel_radius : 0.0553

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 10

  # Base frame_id
  base_frame_id: base_link #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : false
      max_velocity           : 1.5  # m/s
      has_acceleration_limits: true
      max_acceleration       : 5  # m/s^2
      # has_jerk_limits        : true
      # max_jerk               : 4.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           : 2  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 10  # rad/s^2
      # has_jerk_limits        : true
      # max_jerk               : 2.5  # rad/s^3