map_type: costmap

obstacle_range: 4 #2.5
raytrace_range: 4 #3.0
#footprint: [[-0.6, -0.6], [-0.6, 0.6], [0.6, 0.6], [0.6, -0.6]]
footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1]] #.22 is close. What if we make it all buffer tiny frame, was .3,  .1
#robot_radius: 0.7
inflation_radius: 0.9 #was .4, .55 is close, so was .575! # was .55, then .65, .85, .9

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: odom, data_type: LaserScan, topic: $(arg scan), marking: true, clearing: true}
