map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[-0.6, -0.6], [-0.6, 0.6], [0.6, 0.6], [0.6, -0.6]]
footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]] #.22 is close. What if we make it all buffer tiny frame
#robot_radius: 0.7
inflation_radius: 0.85 #was .4, .55 is close, so was .575! # was .55, then .65

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: odom, data_type: LaserScan, topic: $(arg scan), marking: true, clearing: true}
