main_camera_pitch_controller:
    joint: main_camera_pitch_joint
    pid:
        p: 100.0
        i: 0.0
        d: 5.0
    type: effort_controllers/JointPositionController

main_camera_yaw_controller:
    joint: main_camera_yaw_joint
    pid:
        p: 100.0
        i: 0.0
        d: 5.0
    type: effort_controllers/JointPositionController
